# Site settings
title: Peter Strumolo
email: pstrum@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts and comments from a Front-end Developer who helps to make a better web.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pstrum.github.io" # the base hostname & protocol for your site
twitter_username: PeterStrumolo
github_username: pstrum
paginate: 20
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
